services:
  web:
    build: .
    container_name: valsci-web-dev
    ports:
      - "3000:3000"
    environment:
      - FLASK_APP=run.py
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./:/valsci
      - semantic_scholar_data:/valsci/semantic_scholar/datasets
      - queued_jobs:/valsci/queued_jobs
      - saved_jobs:/valsci/saved_jobs
    restart: unless-stopped

  processor:
    build: .
    container_name: valsci-processor-dev
    command: python processor.py
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./:/valsci
      - semantic_scholar_data:/valsci/semantic_scholar/datasets
      - queued_jobs:/valsci/queued_jobs
      - saved_jobs:/valsci/saved_jobs
    restart: unless-stopped
    depends_on:
      - web

volumes:
  semantic_scholar_data:
  queued_jobs:
  saved_jobs: 